import sys; sys.path.append('pyzx-master')
import random, math, os
import pyzx as zx
from fractions import Fraction
from IPython.display import display
import csv
import math


#Want to write and then read in a CSV file that tells us what operations to perform and to which nodes.
#Should be getting dynamically generated by Javascript 
#simply writes a dummy text file with what i think the output from JS will be
with open('updates.csv', 'w', newline='') as file:
    writer = csv.writer(file)
    
    writer.writerow(["s","5","6"])
    writer.writerow(["s", "8","10"])
    writer.writerow(["s", "12", "15"])
    writer.writerow(["s", "11","13"])
    writer.writerow(["u", "8","1","4"," 1","12"])
    writer.writerow(["i", "14","17","r"])
    writer.writerow(["i", "9","16","g"])
    writer.writerow(["ri", "5","2","9"])
    writer.writerow(["ri", "20","8","12"])


 